{% set name = "enchant" %}
{% set version = "2.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/AbiWord/{{ name }}/releases/download/v{{ version }}/enchant-{{ version }}.tar.gz
  sha256: 07915603f4f6889d5caecfddea58a16c1565f340f49c428a7bb7686abbff816e

build:
  number: 0
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('enchant', max_pin='x.x') }}

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - groff  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - glib
    - hunspell
  run:
    - glib
    - hunspell
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - enchant-2 -v  # [unix]

about:
  home: https://abiword.github.io/enchant/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LIB
  summary: enchant spellchecking library

extra:
  recipe-maintainers:
    - izahn
