{% set name = "enchant" %}
{% set version = "2.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/AbiWord/{{ name }}/releases/download/v{{ version }}/enchant-{{ version }}.tar.gz
  sha256: c1c5719f2a597ce3e06c938cfb99fb697da093dea7b857cc004dc1dcf1bba182

build:
  number: 1
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('enchant', max_pin='x.x') }}

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - groff  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - glib
    - hunspell
  run:
    - glib
    - hunspell

test:
  commands:
    - enchant-2 -v  # [unix]

about:
  home: https://abiword.github.io/enchant/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LIB
  summary: enchant spellchecking library

extra:
  recipe-maintainers:
    - asmeurer
    - izahn
