{% set name = "enchant" %}
{% set version = "2.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/rrthomas/{{ name }}/releases/download/v{{ version }}/enchant-{{ version }}.tar.gz
  sha256: 149e224cdd2ca825d874639578b6246e07f37d5b8f3970658a377a1ef46f2e15

build:
  number: 1
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('enchant', max_pin='x.x') }}

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - groff  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - glib
    - hunspell
  run:
    - glib
    - hunspell

test:
  commands:
    - enchant-2 -v  # [unix]

about:
  home: https://rrthomas.github.io/enchant/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LIB
  summary: enchant spellchecking library

extra:
  recipe-maintainers:
    - asmeurer
    - izahn
